### ISSUE TITLE
Station highlight does not clear properly

### ISSUE THREAD

**Issue by harbingerofme** [hex-agon/mastering-mixology#11]
Dunno what edgecase I made, but unchecking "highlight stations" doesn't clear it either.
See image where homogeniser is highlighted, but there's only alembic orders.
![image](https://github.com/user-attachments/assets/9408af5c-f6dc-4837-9c60-84c31ebb8e5e)

**Comment by Xakinator** [comment]
I noticed this as well. If the program picks the Agitator, but you go do the Retort or Alembic instead, the Agitator remains highlighted even after turning in the potion.

**Comment by hex-agon** [comment]
Fixed with 95ae9cc01fa01cf4f749be977c709254cbbd0400
