### ISSUE TITLE
Separate quick-action from station highlight

### ISSUE THREAD

**Issue by philzin** [hex-agon/mastering-mixology#16]
It would be nice to have the option to have the stations light up for quick-action even if the baseline highlighting is off, or if you're making a pot that doesn't match the one the plugin thinks you should be making.

**Comment by HenryBurns** [comment]
As a workaround here, you could set the baseline highlighting opacity to 0, so it's fully transparent. Then you'd still have the quick action highlighting.

A little additional thing here, It'd be nice if we could also have a tick count down to the quick-action for the pump / alambic mixing station.

Considering that it's consistently 5 pumps for the first action (or 7 pumps for any missed action), it could be a cool feature :).

**Comment by Fincher07** [comment]
Agreed. Right now, if you were to make 2 or 3 potions in a row at the stations, the quick-action will only light up for the first potion you make. I think your suggestion would be the best fix.

**Comment by hex-agon** [comment]
Addressed by c034e9e37b433b5e9d78867ebe590a58b12ec3d8
