### ISSUE TITLE
confusing

### ISSUE THREAD

**Issue by johnnybraavo1119** [hex-agon/mastering-mixology#17]
can you add numbers to the tables in relation to the order of the potion? it highlights tables that aren't correct for the potion in your inventory and can end up making the wrong thing and causing a lot of xp loss.

**Comment by fourtwentycoding** [comment]
> can you add numbers to the tables in relation to the order of the potion? it highlights tables that aren't correct for the potion in your inventory and can end up making the wrong thing and causing a lot of xp loss.

With all the changes to the minigame within the last week, there are bound to be bugs. The one you're experiencing right now, is that when there are 2 orders with the same recipe, but different table. It will always prioritize one of the two tables, even when making both potions. I expect the next update will fix all these issues as the current iteration of the plugin only checks the levers' for the recipe, and not the item in your inventory / unfinished potions

**Comment by raiyni** [comment]
This should be fixed with inventory ordering
