### ISSUE TITLE
after downloading this my account was hacked 

### ISSUE THREAD

**Issue by theoneandonlySLIM** [hex-agon/mastering-mixology#23]
10 mins after downloading this plug in i was logged out of my account as somebody was trying to log into it

**Comment by hex-agon** [comment]
All the code in the plugin is publicly available is open to review, you most likely downloaded a fake client and thus got hacked through it.

If you have any further questions join the discord located at https://runelite.net/discord

**Comment by theoneandonlySLIM** [comment]
im in the discord and thats were i downloaded runelite from so if that's the case then the runelite link in the discord is fake then
