### ISSUE TITLE
Same potion different table - Highlighting miss match

### ISSUE THREAD

**Issue by BKers** [hex-agon/mastering-mixology#24]
Hi,

Quick feedback, if you have 2 orders of the same kind (for example 2x mixalot), but with different requirement for mixing it (Cystalize, Homogenise or Concentrate) the highlighting is not changing after making the first one.

I think this can be easly fixed with tracking which ones have been made and adding a check to which potion is finished.

Additionally, Highlighting of the operator handles in their corrisponding colors would be a nice addition, same as when to highlight to click on the mixing vessel when its filled.

Overall great addon!

**Comment by SassanechTTV** [comment]
Having the same issue it does cause a bit of confusion. but overall enjoying it

**Comment by raiyni** [comment]
This should be fixed

**Comment by SassanechTTV** [comment]
it just happened again for me with Liplack liquor one was supposed to be homogenise and other was crystalize but it never showed homogenise it did crystalize twice..
