### ISSUE TITLE
Mastering Mixology Point Balancing

### ISSUE THREAD

**Issue by Hamour65** [hex-agon/mastering-mixology#3]
Could you add an option where it balances points based on rewards, I ran the plugin for 1 hour and I have way more green points than blue, and more blue points are needed to purchase all rewards. Other than that great plugin.

Thank you!
![Screenshot 2024-09-27 041720](https://github.com/user-attachments/assets/52cedfde-28ef-4df6-831e-5bab47742e39)

**Comment by thejdubs** [comment]
#2 when integrated will have various highlight options (balance, exp, specific paste type, etc)

**Comment by HenryBurns** [comment]
Extra callout here, it'd be cool if we could have a rough # of potions until reward tracker assuming we optimize for a specific reward.

**Comment by hex-agon** [comment]
I added a few new strategies for potion order highlighting in the latest update, i'll still add one that tries to balance out reward points in the future.

**Comment by artypoop** [comment]
> I added a few new strategies for potion order highlighting in the latest update that should partially help with this, I'll still add one that tries to balance out reward points in the future.

Looks like the meta-shifted when they added the ability to turn in multiple potions at a time. Can you add the enhancement instead to toggle off specific orders (e.g. MMA/MML/MMM pots)? I think right now the meta is always turn in as many good pots you can simultaneously unless you're restricted with your paste quantity.

**Comment by hex-agon** [comment]
I think i'd be wise to wait a few days to see what jagex settles with before proceeding then

**Comment by raiyni** [comment]
Strategy has been removed
