### ISSUE TITLE
Multiple Potion Support

### ISSUE THREAD

**Issue by Dot145** [hex-agon/mastering-mixology#31]
After the hotfix a day after release, it became possible to turn in multiple potions at once. Oftentimes, the potions require different processing stations, and the order in which you do the stations is very important (it draws from the first item in inventory). Mess up the order of the stations and you aren't fulfilling the order at all. It would be nice to highlight all stations in the current order that the player has mixed the starting potion for and draw numbers 1, 2, or 3 on each station based on their order in the player's inventory. 

For example, if the player has an order of

- Homogenized MML
- Concentrated LLL
- Crystallized MAL

then mixed MML, LLL, and MAL potions in order, the Agitator would be highlighted with a "1", the Retort would be highlighted (perhaps less noticeably?) with a "2", and the Alembic would be highlighted with a "3". If the player switched the order of LLL and MML, then the Retort would get the brighter highlight and the "1" and the Agitator would get the lesser highlight and the "2", and so on based on any inventory rearranging

**Comment by raiyni** [comment]
This should be fixed
