### ISSUE TITLE
Not respecting the strategy chosen

### ISSUE THREAD

**Issue by RobertNash1** [hex-agon/mastering-mixology#32]
Hello! While using the plugin, it seems to be highlighting the incorrect choice almost all of the time today. 

Here is an example, I have it set to Favor Lye

![image](https://github.com/user-attachments/assets/727fad73-a1b8-4001-b87a-f588ff8a626b)

bust you can see that it is highlighting MMA instead of MLL

![image](https://github.com/user-attachments/assets/90226d70-6915-4c4a-91fa-a3745ee61f24)

Additionally, it also seems to highlight potions that I do not have the level requirements for (currently the only one I can't do is MAL).

I have entered and exited the area to try and refresh it, as well as turning the plugin off and on just in case. I have NOT yet uninstalled and re-installed the plugin.

**Comment by fourtwentycoding** [comment]
> Hello! While using the plugin, it seems to be highlighting the incorrect choice almost all of the time today.
> 
> Here is an example, I have it set to Favor Lye
> 
> ![image](https://private-user-images.githubusercontent.com/27237502/372849928-727fad73-a1b8-4001-b87a-f588ff8a626b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzcyNjYsIm5iZiI6MTcyNzg3Njk2NiwicGF0aCI6Ii8yNzIzNzUwMi8zNzI4NDk5MjgtNzI3ZmFkNzMtYTFiOC00MDAxLWI4N2EtZjU4OGZmOGE2MjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDEzNDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMTY0M2Y5NzQwNmU3ZDNiZmZiZDJmZGZhNWE2NTQ0MDI3ZmY0OTAzNTI5YzUxYmMwOWIyMTIwM2Y1YTA2MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KRYPVrgw4WRi07hQx40gPX_CK90uCp7wg4yf5GXFQMs)
> 
> bust you can see that it is highlighting MMA instead of MLL
> 
> ![image](https://private-user-images.githubusercontent.com/27237502/372850114-90226d70-6915-4c4a-91fa-a3745ee61f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzcyNjYsIm5iZiI6MTcyNzg3Njk2NiwicGF0aCI6Ii8yNzIzNzUwMi8zNzI4NTAxMTQtOTAyMjZkNzAtNjkxNS00YzRhLTkxZmEtYTM3NDVlZTYxZjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDEzNDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZWE2MDJmOTM5NGExNTBlODcyNzBhNjQ2YTgxOGI4NjMzMjE1NDdjM2Q2Mjc4NjkxMmIxOTNjNTdjZTg5NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xNRvCcFqnBBrJaWd3kgAi5sG4_rw6KqZXEr-0if4_E8)
> 
> Additionally, it also seems to highlight potions that I do not have the level requirements for (currently the only one I can't do is MAL).
> 
> I have entered and exited the area to try and refresh it, as well as turning the plugin off and on just in case. I have NOT yet uninstalled and re-installed the plugin.


Just curious how you're getting recipes you cannot do when the game doesn't give you the recipes you can't do? Its been like this for almost a week. So either your account is bugged, or you haven't played the minigame and turned in a potion to "refresh" this recipe list. 

Also the game was just updated today. To change the recipes requirements. So the plugin is probably using the old level requirements for the recipes thus you arent getting the recipes you can NOW do highlighted. There were probably some ID changes as well.

**Comment by RobertNash1** [comment]
> > Hello! While using the plugin, it seems to be highlighting the incorrect choice almost all of the time today.
> > Here is an example, I have it set to Favor Lye
> > ![image](https://private-user-images.githubusercontent.com/27237502/372849928-727fad73-a1b8-4001-b87a-f588ff8a626b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzcyNjYsIm5iZiI6MTcyNzg3Njk2NiwicGF0aCI6Ii8yNzIzNzUwMi8zNzI4NDk5MjgtNzI3ZmFkNzMtYTFiOC00MDAxLWI4N2EtZjU4OGZmOGE2MjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDEzNDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMTY0M2Y5NzQwNmU3ZDNiZmZiZDJmZGZhNWE2NTQ0MDI3ZmY0OTAzNTI5YzUxYmMwOWIyMTIwM2Y1YTA2MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KRYPVrgw4WRi07hQx40gPX_CK90uCp7wg4yf5GXFQMs)
> > bust you can see that it is highlighting MMA instead of MLL
> > ![image](https://private-user-images.githubusercontent.com/27237502/372850114-90226d70-6915-4c4a-91fa-a3745ee61f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzcyNjYsIm5iZiI6MTcyNzg3Njk2NiwicGF0aCI6Ii8yNzIzNzUwMi8zNzI4NTAxMTQtOTAyMjZkNzAtNjkxNS00YzRhLTkxZmEtYTM3NDVlZTYxZjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDEzNDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZWE2MDJmOTM5NGExNTBlODcyNzBhNjQ2YTgxOGI4NjMzMjE1NDdjM2Q2Mjc4NjkxMmIxOTNjNTdjZTg5NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xNRvCcFqnBBrJaWd3kgAi5sG4_rw6KqZXEr-0if4_E8)
> > Additionally, it also seems to highlight potions that I do not have the level requirements for (currently the only one I can't do is MAL).
> > I have entered and exited the area to try and refresh it, as well as turning the plugin off and on just in case. I have NOT yet uninstalled and re-installed the plugin.
> 
> Just curious how you're getting recipes you cannot do when the game doesn't give you the recipes you can't do? Its been like this for almost a week. So either your account is bugged, or you haven't played the minigame and turned in a potion to "refresh" this recipe list.
> 
> Also the game was just updated today. To change the recipes requirements. So the plugin is probably using the old level requirements for the recipes thus you arent getting the recipes you can NOW do highlighted. There were probably some ID changes as well.



I just started the minigame yesterday. Last night it seemed that it gave me MAL that I couldn't do(?) but today it does not seem to be the case.

And yeah, if the recipes have changed then it would highlight the wrong ones for sure, possibly that will be resolved alongside support for multiple options at once  (and maybe lever highlighting too :) )

**Comment by raiyni** [comment]
This should be fixed
