### ISSUE TITLE
XP strategy is highlighting incorrect recipe

### ISSUE THREAD

**Issue by myellowsnow** [hex-agon/mastering-mixology#33]
Not sure if they changed the xp rates, but im getting multiple wrong suggested potions when my strategy is set to XP

**Comment by PsiLupan** [comment]
XP rates were changed as part of today's patch, yeah.

This has the table:
https://secure.runescape.com/m=news/rewards-and-xp-improvements---varlamore-the-rising-darkness

**Comment by Speeddymon** [comment]
Not sure if it's related to this or separate, but happy to file a separate report if needed -- I'm having a similar issue; a mismatch between the highlighted recipe in the minigame overlay and the table that's highlighted

![image](https://github.com/user-attachments/assets/7487727a-8fdb-4334-8f83-a0b1b3113437)

In this case, the homogenized MMM is highlighted in the overlay but the Alembic is highlighted, which crystallizes the potion. Which one should I do? Homogenize it, or crystallize it? I have an order for both a crystallized MMM and a homogenized MMM.

**Comment by raiyni** [comment]
It's highlighting the last potion you picked up. Fix was waiting on this most recent update as Jagex has made many changes in the last week to it.

**Comment by whiitehead** [comment]
I couldn't wait any longer, need to abuse these xp rates before they get nerfed.

https://github.com/runelite/plugin-hub/pull/6708

**Comment by myellowsnow** [comment]
omg its perfect now. GOAT
