### ISSUE TITLE
Color converyor belt depending on valid potions in inventory

### ISSUE THREAD

**Issue by Antoine-dh** [hex-agon/mastering-mixology#39]
Highlight in red for example if you do not have any valid potion to fulfill the current order in your inventory, green if you do.
This can be useful to quickly react while fulfilling multiple orders at a time with lots of potions prepared beforehand as shown in this [strategy](https://www.youtube.com/watch?v=Wt3CndDxnGU)

Optionally make it swap menu entry if you do not have any valid potion to prevent accidental missclick

**Comment by BlueSoapTurtle** [comment]
Currently potions have an ID when unprocessed and another id when processed but there's no way to see what machine the potion was used on so I'm unsure if this is possible :/

**Comment by raiyni** [comment]
Correct, this is not possible to determine.
