### ISSUE TITLE
UI cuts off, name too long

### ISSUE THREAD

**Issue by artypoop** [hex-agon/mastering-mixology#4]
Hello, the UI gets cut off for me as shown below:

![RuneLite_sHXcUCSKYN](https://github.com/user-attachments/assets/44588350-5f59-490c-be00-f4462f624883)

**Comment by artypoop** [comment]
Thanks for the quick fix <3 great plugin

**Comment by artypoop** [comment]
ty

**Comment by hex-agon** [comment]
Hey, if you walk out & in of the room it should re-size properly, I'll be looking at why this happens but it's at the bottom of the list for now.

**Comment by raiyni** [comment]
This should be fixed with the latest game update
