### ISSUE TITLE
Ready indicator not resetting properly

### ISSUE THREAD

**Issue by Tzrt** [hex-agon/mastering-mixology#43]
After sending off an order, the 'ready!' indicator remains on the potion list at the top left, meaning the 'helper' letter code doesn't appear.

![image](https://github.com/user-attachments/assets/d0cc6934-298e-4ca7-af4c-3a3dddf91617)

**Comment by raiyni** [comment]
Can you reliably reproduce this? Do you have steps?

**Comment by Tzrt** [comment]
Steps to reproduce 
1. Make 1-3 potions that are part of your current order.
2. Process them correctly, as instructed.
3. Turn them in.
4. At this point, the problem presents itself - your order updates but the 'Ready!' indicator remains from the previous order. If you are submitting a partial order, the Ready! indicator remains only on the same lines as those potions you completed (if you only fulfilled the middle potion, only the middle potion on your new order shows 'Ready!'.
5. As soon as you pull a lever to add ingredients to the mixer, the Ready! indicator disappears and is replaced by the 3 letter helper.

It can be reliably reproduced, and happens to me each and every run. I am performing the minigame as normal, using the mechanics to speed up potion processing. Tested without using speed-up mechanics, same result. I have some tile markers labeled in the area, plus object markers on the different objects that are interacted with. Please note that the '3 letter helper' returns as normal as soon as your start pulling levers to add ingredients to the mixer, though the expected behavior would be that the 3 letter helper updates as soon as you turn in an order. 

Testing a few individual settings to see if any specific setting enabled/disabled corrects issue -
Highlight levers - No change on or off
Highlight quick-action events - No change on or off
Highlight stations - No change on or off
Identify potions - No change on or off

![image](https://github.com/user-attachments/assets/8085019b-458a-4345-b724-fcca6c404a1f)

**Comment by hex-agon** [comment]
If you pull a lever, does the UI update correctly?

**Comment by Tzrt** [comment]
Yes -
>Please note that the '3 letter helper' returns as normal as soon as your start pulling levers to add ingredients to the mixer, though the expected behavior would be that the 3 letter helper updates as soon as you turn in an order.

**Comment by hex-agon** [comment]
I see the issue, if you want to fix it set the strategy to anything but none

**Comment by Blugamma** [comment]
I have also noticed that if you have the same order that uses the same machine the ready feature only detects on one of the potions.
![image](https://github.com/user-attachments/assets/e3fb2beb-ba58-4e74-9a4f-2828ef88564c)
So in this image I have 2 Mystic Mana amalgam on my orders. But my inventory has two homogenised Mythic Mana amalgams but the orders only detected 1 of them to be ready.

**Comment by Blugamma** [comment]
I also had my strategy on None. So this could be the issue.

**Comment by hex-agon** [comment]
Fixed with e08228027b433d35e408ab3b59f0ecec86f5bdfe

**Comment by artypoop** [comment]
> Fixed with [e082280](https://github.com/hex-agon/mastering-mixology/commit/e08228027b433d35e408ab3b59f0ecec86f5bdfe)

If strategy is none, it takes a considerably longer time for the "ready!" to reset compared to having a strategy on. It resets when you're close to the lever, and it doesn't reset if you're walking to the lever. Only resets once you've touched a lever.
