### ISSUE TITLE
Ready Indicator Update after each turn-in

### ISSUE THREAD

**Issue by RonnyTommy548** [hex-agon/mastering-mixology#45]
I noticed that the ready indicator only updates when you finish crafting a potion. For the method that involves turning-in the majority of a full inventory of potions, it would be nice if the ready indicator would update after each potion turn-in. This way when I'm near the end of my inventory I wouldn't have to be manually scanning my inventory + thinking about the order to tell if I have any matches.

**Comment by raiyni** [comment]
This is not possible as the type of potion made from the stations isn't trackable

**Comment by RonnyTommy548** [comment]
The ready indicator seems to work when you make the potion initially, I'm guessing since in that moment the plugin knows that you're using a certain potion type on a certain station, I guess it could go off the chat message too "you finish **crystallising** the X". Would it be feasible to collect this information in some saved state inside the plugin, so it could track what has entered/left your inventory for the purpose of achieving the ready indicator updates?

Here's an example - there could be a table that would have 3x slots per type of potion (to account for all combinations). For every chat message corresponding to creating a potion, e.g. "you finish crystallising the Liplack liquor", then that entry of the table would get +1 to indicate how many potions of that type the player has in their inventory. Then when the player goes to turn in the potions, for every message "You deposit some Liplack liquor and fulfil an order" (or the failure message), it would subtract 1 from the corresponding entry in the table.

With this there would probably be a lot of edge cases like what if the player leaves the area and banks some of these potions. So maybe this isn't practical, let me know what you think

**Comment by raiyni** [comment]
That could be a band-aid but I would imagine reordering potions in your inventory would cause issues since there is no state attached to the items. Ex, you have two LLL and swap them--the plugin wouldn't know what was moved.

**Comment by hex-agon** [comment]
I don't want to support the full inv of pots method because there's no reliable way of tracking how a potion was refined
