### ISSUE TITLE
Great improvements!

### ISSUE THREAD

**Issue by Speeddymon** [hex-agon/mastering-mixology#54]
Hi, I just wanted to write a thank you. I downloaded the latest update this morning and everything works perfectly plus I see some new features. This plugin is super great now! You are awesome.

**Comment by Speeddymon** [comment]
It even switches the table highlight as you reorder your inventory. *chef's kiss*

**Comment by raiyni** [comment]
Thank you, on behalf of hex-agon you can  contact us in the Runelite discord too.
