### ISSUE TITLE
Customize notification sounds

### ISSUE THREAD

**Issue by Speeddymon** [hex-agon/mastering-mixology#56]
Hello,

Runelite and some plugins like Idle Notifier have a settings icon next to the checkbox for enabling and disabling notifications that allows you to customize the notification. I'd like to see that same settings icon and settings for the Notify DigWeed checkbox please.

Digweed is actually important during this minigame, so I want to select "Custom" to play the global custom notification sound I added to my ~/.runelite directory rather than the default notification sound.

**Comment by hex-agon** [comment]
Should be fixed with cf4433c8413e59eb9e70df2ce1607fb479ae398e
