### ISSUE TITLE
New strategies: Evenly distributing reagent usage, and recovering from reagent imbalance (names TBD)

### ISSUE THREAD

**Issue by Speeddymon** [hex-agon/mastering-mixology#58]
I've been focusing on XP but I want to switch now to focusing on getting my points distribution evened out. I have far more points for Lye and Mox than I do for Aga, so I thought of two new strategies.

1. Prioritizing that when I make potions, the plugin keeps the point distribution even (regardless of whether there is an imbalance currently, or not).
    * So if I have 2400, 2300, 1800, then the plugin should highlight the mixtures that will result in the least imbalance and recover from the imbalance as soon as possible.
2. Prioritizing getting rid of any imbalance.
    * So if I have again 2400, 2300, 1800, then the plugin should highlight the mixtures that will result in the lowest point value (Lye in my case, at 1800) having the highest gains. In case no mixture contributes toward the lowest point value, then focus on the second lowest point value. If none of them contributes toward that either, then consider coloring all mixtures on the overlay red.

**Comment by raiyni** [comment]
Strategy has been removed
