### ISSUE TITLE
Detect already-completed left-over mixtures

### ISSUE THREAD

**Issue by Speeddymon** [hex-agon/mastering-mixology#59]
![image](https://github.com/user-attachments/assets/b4734353-01a3-4950-9209-174b75677c7b)

The LLL mixture pictured here in the bottom left was accidentally made when I didn't have an order for it. It is a crystallized mixture, so it should be marked as done in the overlay on the top left now that I do have an order for it, but it's not getting recognized.

**Comment by raiyni** [comment]
This is not possible to reliably detect as the information needed to see the table type isn't transmitted unfortunately.

**Comment by Speeddymon** [comment]
Unfixable at this time.

**Comment by dhouck** [comment]
Would it be possible to do a version of this where it only detects the already-completed potion when you `Inspect` it?  That gets all the information available.

If that works, the same partial solution would work for #69 and #75, where it could display as `?` if unknown.  Thatʼs how things like essence pouches work.

**Comment by raiyni** [comment]
No it's still too easy to break because you are only tracking inventory location

**Comment by TheDeviantCrafter** [comment]
The Simplifying Mixology plugin seems to have access to this information. This screenshot has 2 LLL potions, left concentrated, right unprocessed. 

<img width="306" height="416" alt="Image" src="https://github.com/user-attachments/assets/45fa718e-2520-4f19-be70-e1bbef303e53" />

**Comment by TheDeviantCrafter** [comment]
Another option is to only track when the player has a premixed, but unprocessed potion that matches the current order. If a new order comes in and the player has the right unprocessed potion in their inventory, change the top left text to "Potion name (mixed)" and highlight the item in the inventory. Prepping potions that way is still more efficient than making 3 at a time.
