### ISSUE TITLE
Done! indicator not updating with successive potion order completions

### ISSUE THREAD

**Issue by lbito** [hex-agon/mastering-mixology#62]
When making potions in bulk, the Done! indicator does not appear for potion orders until a new potion is processed.
Having the indicator update on potion order completed as well would be beneficial for a bulk strategy

**Comment by raiyni** [comment]
It's not possible to see the table type of a portion after it's completed. We can assume table types for the first time based on knowing we are using an unprocessed potion on a table and getting a processed potion back.
