### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by Hairfagri** [hex-agon/mastering-mixology#64]
- It doesn't highlight concentrate.
- the highlight doesn't disappear when "boost" are used.
- it doesn't allways show wich table you should use.
- it still show highlight on the potion which give the best exp, even when strategy are set to "none"

- Doesn't know if this is the plugin or the game, but sometimes it makes a sound, as when you can boost, but when the sound comes, you actually can't use boost.

it would also be nice with a better notification when digweed spawn.

**Comment by raiyni** [comment]
Highlighting is fixed on master and strategy is removed
