### ISSUE TITLE
Suggestion: Re-order the list of potion orders so that same station orders are next to eachother

### ISSUE THREAD

**Issue by vattukarkkik** [hex-agon/mastering-mixology#66]
This would simplify making the potions.

![reorder-example](https://github.com/user-attachments/assets/b2cac88b-3108-48e0-91fc-ff2eb17ee37d)

**Comment by averagegatsby29** [comment]
+1, also would be nice to always have the homogenizer as last (or to have this be a customizable option) because it's 1 tick closer to the delivery station
