### ISSUE TITLE
Suggestion: check new orders against existing potions in inventory

### ISSUE THREAD

**Issue by ingmarins** [hex-agon/mastering-mixology#67]
When you accidentally mix the wrong potion and finish it, and hand in the other correct potions, next batch of orders doesn't say "done!" even though I happen to have exactly that potion already in inventory. Even if I rightclick-inspect the potion, it still doesn't say "done!"

**Comment by raiyni** [comment]
see https://github.com/hex-agon/mastering-mixology/issues/59
