### ISSUE TITLE
Station Highlight is slow

### ISSUE THREAD

**Issue by Lmbabel** [hex-agon/mastering-mixology#7]
The station highlight is the tick after you pick up, which is genius for its ability to match what you get from the mixing vessel. However, this does mean you still have to use mental stack to check the station in advance if you want to be efficient.

Proposed solution:
An option to pre-highlight the station you were going to if you're following the current strategy.

**Comment by HenryBurns** [comment]
Additional comment here, If you've premade potions it circumvents the current highlighting system. The proposed solution would fix this issue too.

**Comment by hex-agon** [comment]
Should be addressed by 8d8343756af8cadf4e479dc0a5dc992766c54782
