### ISSUE TITLE
Order Sorting by Station is Reversed

### ISSUE THREAD

**Issue by Atom-Cats** [hex-agon/mastering-mixology#93]
First of all great plugin, I love it. The current sorting of the potion stations, top to bottom is: Homogenise then Concentrate then Crystallize. This cycle, running from levers, to each station then to the conveyor belt takes 9 ticks (5.4 seconds)

If the order was Crystallize then Concentrate then Homogenise, the same cycle takes 7 ticks (4.2 seconds). This saves 2 ticks per potion order when all three stations are required, and at least 1 tick otherwise (unless all one station.

Thanks for looking into this

**Comment by BlueSoapTurtle** [comment]
Fixed by #85 alternatively #80 just need a release
